In [13]:
import pandas as pd

In [24]:
df = pd.read_csv("company.csv")
df

,job id,job name,company,skill
0,1610,Dashboard Development,Blackcoffer,"php,html,css,javascript,python,mongodb,nodejs"
1,1611,Java Development and Testing,NextGen Invent Corporation,"java,sql"
2,1612,Virtual Reality/Augmented Reality(VR/AR) App D...,Param Labs Private Limited,"c,adobe,photoshop,unity,physics,imageprocessin..."
3,1613,Mobile App Development,Evineon Technologies,"java,ios,android"
4,1614,Backend Web Development,IIT Bombay,"java,javascript,jquery,python,bootstrap,django..."
5,1615,Artificial Intelligence & Machine Learning,Scuti Tech Labs,"java,python,ml,rprogramming"
6,1616,Data Science,Scuti Tech Labs,"ml,imageprocessing"
7,1617,Embedded Systems,Concinnity Agro2o Private Limited,"linux,unix,ml,embeddedsystem,c,cpp,iot"
8,1618,Robotics/Drones Design,11Mantras,"embeddedsystem,c,cpp"
9,1619,Artificial Intelligence,SME MaXX,"python,ml,rprogramming"
10,1620,Big Data,ALYTSEE Technologies,"java,python,hadoop"
11,1621,Analytics And Big Data,GraduFund,"java,python,sql,django,hadoop"
12,1622,Application Development for IoT And Cloud Comp...,Fermedicius Labs,"java,php,css,javascript,cloudcomputing,mongodb..."
13,1623,Cloud Iot Integration,Untodden Labs,"cloudcomputing,c,linux,cpp"
14,1624,Cyber Security and Infrastructure,Zenshanti,"cloudcomputing,wordpress,linux,dbms"
15,1625,Web Development,Signotrix Technologies,"html,javascript"
16,1626,Full Stack Development,Travel dâ€™globe,"javascript,python,sql,nodejs,json"
17,1627,Full Stack Development,Blackcoffer,"html,css,javascript,mongodb,nodejs"
18,1628,Full Stack Web Development,Sense8 Technologies,"javascript,datastructures,angularjs,nodejs"
19,1629,MERN Stack Development,Blackcoffer,"mongodb,nodejs,reactjs"
20,1630,Full Stack Development,Daphnis Labs Technologies Private Limited,"php,javascript,sql,mongodb,angularjs,nodejs,sq..."
21,1631,Software Development (Full Stack),Emuron Technologies,"html,css,python,linux,cpp,dbms"
22,1632,Front End Development,IdeaVillage,"php,html,sql,css,javascript,bootstrap"
23,1633,Image Processing,VasundharaaGeo Technologies Private Limited,"ml,imageprocessing"
24,1634,iOS App Development,Kkekk Incorporation,"swift,ios"
25,1635,Mobile App Development,Minushia,"java,ios,android"
26,1636,Mobile App Development,Decision Fiction,"swift,ios"
27,1637,Remote Python Development,Perseus Automations,"python,cpp"
28,1638,Graphic Design,Internshala,"photoshop,adobe"
29,1639,Software Development (Full Stack),Agneyas Labs Private Limited,"python,linux,c,cpp"
30,1640,Software Dvelopment,Sun Bots,"html,css,javascript,python"

In [28]:
from collections import defaultdict
company_id = defaultdict(int)
company_name = df['company']
company_name1 = list(company_name)
company_name = list(set(company_name1))
print(company_name1)
print()
print(company_name)
com_id=[]
#print(type(company_name),company_name)
cid=10
for i in company_name:
    company_id[i] = cid
    cid = cid+1
#print(company_id)
for c in company_name1:
    #print(c,company_id[c])
    com_id.append(company_id[c])
print(com_id)
com_id = pd.DataFrame(com_id)
com_id
df['com_id'] = com_id

['Blackcoffer', 'NextGen Invent Corporation', 'Param Labs Private Limited', 'Evineon Technologies', 'IIT Bombay', 'Scuti Tech Labs', 'Scuti Tech Labs', 'Concinnity Agro2o Private Limited', '11Mantras', 'SME MaXX', 'ALYTSEE Technologies', 'GraduFund', 'Fermedicius Labs', 'Untodden Labs', 'Zenshanti', 'Signotrix Technologies', 'Travel dâ€™globe', 'Blackcoffer', 'Sense8 Technologies', 'Blackcoffer', 'Daphnis Labs Technologies Private Limited', 'Emuron Technologies', 'IdeaVillage', 'VasundharaaGeo Technologies Private Limited', 'Kkekk Incorporation', 'Minushia', 'Decision Fiction', 'Perseus Automations', 'Internshala', 'Agneyas Labs Private Limited', 'Sun Bots']

['IdeaVillage', 'IIT Bombay', 'Decision Fiction', 'Agneyas Labs Private Limited', 'NextGen Invent Corporation', 'Kkekk Incorporation', 'Signotrix Technologies', 'GraduFund', 'Daphnis Labs Technologies Private Limited', 'Perseus Automations', 'Zenshanti', 'Internshala', 'Sun Bots', 'Sense8 Technologies', 'SME MaXX', 'Emuron Technologies', 'Untodden Labs', 'Evineon Technologies', 'Concinnity Agro2o Private Limited', 'VasundharaaGeo Technologies Private Limited', 'Travel dâ€™globe', 'Blackcoffer', 'ALYTSEE Technologies', 'Param Labs Private Limited', 'Minushia', 'Scuti Tech Labs', 'Fermedicius Labs', '11Mantras']
[31, 14, 33, 27, 11, 35, 35, 28, 37, 24, 32, 17, 36, 26, 20, 16, 30, 31, 23, 31, 18, 25, 10, 29, 15, 34, 12, 19, 21, 13, 22]

In [16]:
dfs = pd.read_csv("unique_skills.csv",header=None)
dfs.head()
#job_skill = list(df['skill'])
#for i in job_skill:
    #print(i)
dfs = list(dfs[0])
job_id = defaultdict(int)
for i in range(len(dfs)):
    job_id[dfs[i]]=i
job_id
job=[]
job_skill = list(df['skill'])
for i in range(len(job_skill)):
    j = job_skill[i].split(',')
    x=""
    for k in range(len(j)):
        x = x+str(job_id[j[k]])+','
    print(x)
    x=x.rstrip(',')
    job.append(x)
#print("job = ",job)
job = pd.DataFrame(job)
job.to_csv("aman.csv",index=False,header=None)

0,1,2,3,4,5,6,
7,8,
9,10,11,12,13,14,15,16,
7,15,16,
7,3,17,4,18,19,20,21,
7,4,22,23,
22,14,
24,25,22,26,9,27,28,
26,9,27,
4,22,23,
7,4,29,
7,4,8,19,29,
7,0,2,3,30,5,27,31,16,
30,9,24,27,
30,32,24,21,
1,3,
3,4,8,6,33,
1,2,3,5,6,
3,34,20,6,
5,6,35,
0,3,8,5,20,6,8,35,
1,2,4,24,27,21,
0,1,8,2,3,18,
22,14,
36,15,
7,15,16,
36,15,
4,27,
11,10,
4,24,9,27,
1,2,3,4,

In [17]:
df['jobi']=job

In [18]:
df

,job id,job name,company,skill,com_id,jobi
0,1610,Dashboard Development,Blackcoffer,"php,html,css,javascript,python,mongodb,nodejs",31,"0,1,2,3,4,5,6"
1,1611,Java Development and Testing,NextGen Invent Corporation,"java,sql",14,"7,8"
2,1612,Virtual Reality/Augmented Reality(VR/AR) App D...,Param Labs Private Limited,"c,adobe,photoshop,unity,physics,imageprocessin...",33,"9,10,11,12,13,14,15,16"
3,1613,Mobile App Development,Evineon Technologies,"java,ios,android",27,"7,15,16"
4,1614,Backend Web Development,IIT Bombay,"java,javascript,jquery,python,bootstrap,django...",11,"7,3,17,4,18,19,20,21"
5,1615,Artificial Intelligence & Machine Learning,Scuti Tech Labs,"java,python,ml,rprogramming",35,"7,4,22,23"
6,1616,Data Science,Scuti Tech Labs,"ml,imageprocessing",35,"22,14"
7,1617,Embedded Systems,Concinnity Agro2o Private Limited,"linux,unix,ml,embeddedsystem,c,cpp,iot",28,"24,25,22,26,9,27,28"
8,1618,Robotics/Drones Design,11Mantras,"embeddedsystem,c,cpp",37,"26,9,27"
9,1619,Artificial Intelligence,SME MaXX,"python,ml,rprogramming",24,"4,22,23"
10,1620,Big Data,ALYTSEE Technologies,"java,python,hadoop",32,"7,4,29"
11,1621,Analytics And Big Data,GraduFund,"java,python,sql,django,hadoop",17,"7,4,8,19,29"
12,1622,Application Development for IoT And Cloud Comp...,Fermedicius Labs,"java,php,css,javascript,cloudcomputing,mongodb...",36,"7,0,2,3,30,5,27,31,16"
13,1623,Cloud Iot Integration,Untodden Labs,"cloudcomputing,c,linux,cpp",26,"30,9,24,27"
14,1624,Cyber Security and Infrastructure,Zenshanti,"cloudcomputing,wordpress,linux,dbms",20,"30,32,24,21"
15,1625,Web Development,Signotrix Technologies,"html,javascript",16,"1,3"
16,1626,Full Stack Development,Travel dâ€™globe,"javascript,python,sql,nodejs,json",30,"3,4,8,6,33"
17,1627,Full Stack Development,Blackcoffer,"html,css,javascript,mongodb,nodejs",31,"1,2,3,5,6"
18,1628,Full Stack Web Development,Sense8 Technologies,"javascript,datastructures,angularjs,nodejs",23,"3,34,20,6"
19,1629,MERN Stack Development,Blackcoffer,"mongodb,nodejs,reactjs",31,"5,6,35"
20,1630,Full Stack Development,Daphnis Labs Technologies Private Limited,"php,javascript,sql,mongodb,angularjs,nodejs,sq...",18,"0,3,8,5,20,6,8,35"
21,1631,Software Development (Full Stack),Emuron Technologies,"html,css,python,linux,cpp,dbms",25,"1,2,4,24,27,21"
22,1632,Front End Development,IdeaVillage,"php,html,sql,css,javascript,bootstrap",10,"0,1,8,2,3,18"
23,1633,Image Processing,VasundharaaGeo Technologies Private Limited,"ml,imageprocessing",29,"22,14"
24,1634,iOS App Development,Kkekk Incorporation,"swift,ios",15,"36,15"
25,1635,Mobile App Development,Minushia,"java,ios,android",34,"7,15,16"
26,1636,Mobile App Development,Decision Fiction,"swift,ios",12,"36,15"
27,1637,Remote Python Development,Perseus Automations,"python,cpp",19,"4,27"
28,1638,Graphic Design,Internshala,"photoshop,adobe",21,"11,10"
29,1639,Software Development (Full Stack),Agneyas Labs Private Limited,"python,linux,c,cpp",13,"4,24,9,27"
30,1640,Software Dvelopment,Sun Bots,"html,css,javascript,python",22,"1,2,3,4"

In [19]:
df.to_csv('out.csv',index=False)

In [20]:
df = pd.read_csv("out.csv")
df.head()

,job id,job name,company,skill,com_id,jobi
0,1610,Dashboard Development,Blackcoffer,"php,html,css,javascript,python,mongodb,nodejs",31,"0,1,2,3,4,5,6"
1,1611,Java Development and Testing,NextGen Invent Corporation,"java,sql",14,"7,8"
2,1612,Virtual Reality/Augmented Reality(VR/AR) App D...,Param Labs Private Limited,"c,adobe,photoshop,unity,physics,imageprocessin...",33,"9,10,11,12,13,14,15,16"
3,1613,Mobile App Development,Evineon Technologies,"java,ios,android",27,"7,15,16"
4,1614,Backend Web Development,IIT Bombay,"java,javascript,jquery,python,bootstrap,django...",11,"7,3,17,4,18,19,20,21"